/*
 * generated by Xtext 2.18.0.M3
 */
package de.nicogreve.dsl.expressions


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ExpressionsStandaloneSetup extends ExpressionsStandaloneSetupGenerated {

	def static void doSetup() {
		new ExpressionsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
