/*
 * generated by Xtext 2.18.0.M3
 */
package de.nicogreve.dsl.expressions.ide


/**
 * Use this class to register ide components.
 */
class ExpressionsIdeModule extends AbstractExpressionsIdeModule {
}
