/*
 * generated by Xtext 2.18.0.M3
 */
package de.nicogreve.dsl.expressions.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class ExpressionsWebModule extends AbstractExpressionsWebModule {
}
