/*
 * generated by Xtext 2.18.0.M3
 */
package de.nicogreve.dsl.expressions.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ExpressionsProposalProvider extends AbstractExpressionsProposalProvider {
}
